name: "Server Deployment" 

on: push

jobs: 
	deployment:   
	runs-on: ubuntu-latest   
  
	steps:    
	- uses: actions/checkout@v2      
	- name: Deploy code to Server     
	env:       
		SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}     
	run: |       
		echo $SSH_KEY
    cd /var/www/html/cnaiapp       
    git pull origin main
    npm run build
    pm2 stop all
    pm2 start