name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          exec bash \-l
          cd /var/www/html/cnaiapp      
          git pull git@github.com:vencho-mdp/cnaiapp.git
          npm install
          npx nuxt build
          pm2 stop all
          pm2 start
